Image scale patch
codemorphist/DigitalGarden pull request #33
Opened 2024-05-28 20:44 UTC by codemorphist

Оновлення:
- Збільшений розмір зображення до 1024x1024
- Тепер зображення виглядають пропорційно на канвасах різного розміру

2024-05-29 13:00 UTC, codemorphist commented on plant_generator/plant_generator/genom.py
> +
Тут я переробив так щоб коли `size_from_ancestor` був 0, то довжина залишалася така яка є, а не ставала нулем, аналогічно і для `size_from_level`

2024-05-29 13:00 UTC, codemorphist commented on app/generator_frame.py
> +        r = abs(circle.radius) + 1
Значення `radius` беру абсолютне для того, щоб малювати коло з радіусом -10 малювалося як коло з радіусом 10 (через специфіку бібліотеки Pillow)

2024-05-30 19:04 UTC, karbyshevillia requested changes
`def back():
            self.plant_frame.stop_drawing()
            self.controller.show_frame("Menu")
        # Back button
        self.back_button = ttk.Button(self, text="Back",
                                      command=lambda: back())
        self.configure_widgets()`

Ось цієї штуки у PlantGeneratorFrame недостатньо; тоді генерація не відновлюється знову переході на цей фрейм. Плюс це треба буде зробити для інших фреймів. Треба зробити, я вважаю, "прапорець" у Root, який буде казати усім PlantFrame у фреймі, який зараз на екрані, щоб вони зупинили/відновили роботу

2024-05-30 19:04 UTC, karbyshevillia commented on app/mass_smash_frame.py
> +                                      self.genome_view.index(next_item) + 1)
"+1" не треба, так воно зміщує на дві позиції

2024-05-30 19:24 UTC, merged